FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -q
COPY src ./src
RUN mvn package -DskipTests -q

FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:1.20

ENV LANGUAGE='en_US:en'

WORKDIR /deployments

COPY --chown=185 --from=build /app/target/quarkus-app/lib/ ./lib/
COPY --chown=185 --from=build /app/target/quarkus-app/*.jar ./
COPY --chown=185 --from=build /app/target/quarkus-app/app/ ./app/
COPY --chown=185 --from=build /app/target/quarkus-app/quarkus/ ./quarkus/

EXPOSE 8080

USER 185

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]