# Configuracion de la BD --> postgresql
quarkus.datasource.db-kind=postgresql

# Configuracion de REST y JSON
quarkus.jackson.write-dates-as-timestamps=false

# Configuracion de OpenAPI y SwaggerUI
quarkus.swagger-ui.always-include=true

# Mailer
quarkus.mailer.mock=true
quarkus.mailer.from=noreply@almedin.com

# JWT
mp.jwt.verify.issuer=almedin-backend

# Scheduler
almedin.reminder.hours-before=24
almedin.reminder.cron=0 0 8 * * ?

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=classpath:db/migration
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.smallrye-openapi.path=/openapi
mp.openapi.extensions.smallrye.info.title=Almedin Obra Social API
mp.openapi.extensions.smallrye.info.version=1.0.0

# Health
quarkus.smallrye-health.ui.always-include=true

# Mapstruct
quarkus.mapstruct.injection-strategy=constructor

# Cache
quarkus.cache.caffeine."specialists".expire-after-write=5M
quarkus.cache.caffeine."schedules".expire-after-write=10M
quarkus.cache.caffeine."unavailability".expire-after-write=10M
quarkus.cache.caffeine."specialists".maximum-size=100
quarkus.cache.caffeine."schedules".maximum-size=500
quarkus.cache.caffeine."unavailability".maximum-size=500

# ---------------------------------------------------------------------------------------------

# PEFIL DEV
%dev.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/almedin_db}
%dev.quarkus.datasource.username=${DB_USER:postgres}
%dev.quarkus.datasource.password=${DB_PASSWORD:postgres}
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.flyway.baseline-on-migrate=true
%dev.quarkus.flyway.baseline-version=1
%dev.quarkus.datasource.jdbc.acquisition-timeout=30
%dev.mp.jwt.verify.publickey.location=keys/public.pem
%dev.smallrye.jwt.sign.key.location=keys/private.pem
%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=/.*/
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
%dev.quarkus.http.cors.headers=accept,Content-Type,Authorization
%dev.quarkus.http.cors.access-control-allow-credentials=true
%dev.app.cookie.secure=false

# ---------------------------------------------------------------------------------------------

# PERFIL TEST
%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=postgres:16
%test.quarkus.flyway.migrate-at-start=true
%test.quarkus.hibernate-orm.schema-management.strategy=none
%test.quarkus.mailer.mock=true
%test.quarkus.scheduler.enabled=false
%test.quarkus.datasource.devservices.container-env.TZ=UTC
%test.quarkus.datasource.devservices.container-env.PGTZ=UTC

#%test.mp.jwt.verify.publickey.location=keys/public.pem
#%test.smallrye.jwt.sign.key.location=keys/private.pem

%test.app.cookie.secure=false

# ---------------------------------------------------------------------------------------------

# PERFIL PROD
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.mailer.host=${MAIL_HOST}
%prod.quarkus.mailer.port=${MAIL_PORT}
%prod.quarkus.mailer.start-tls=REQUIRED
%prod.quarkus.mailer.username=${MAIL_USERNAME}
%prod.quarkus.mailer.password=${MAIL_PASSWORD}
%prod.quarkus.mailer.from=${MAIL_FROM}
%prod.quarkus.mailer.mock=false
%prod.quarkus.flyway.migrate-at-start=true
%prod.quarkus.hibernate-orm.schema-management.strategy=none
%prod.quarkus.hibernate-orm.log.sql=false
%prod.quarkus.flyway.baseline-on-migrate=true
%prod.quarkus.flyway.baseline-version=1
%prod.quarkus.datasource.jdbc.acquisition-timeout=30
%prod.quarkus.datasource.jdbc.initial-size=1
%prod.quarkus.datasource.jdbc.min-size=1
%prod.quarkus.datasource.jdbc.max-size=5
%prod.smallrye.jwt.sign.key=${JWT_PRIVATE_KEY}
%prod.mp.jwt.verify.publickey=${JWT_PUBLIC_KEY}
%prod.quarkus.http.cors.enabled=true
%prod.quarkus.http.cors.origins=${FRONTEND_URL}
%prod.quarkus.http.cors.methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
%prod.app.cookie.secure=true
%prod.quarkus.http.cors.headers=Content-Type,Authorization,accept
%prod.quarkus.http.cors.access-control-allow-credentials=true