# Configuracion de la BD --> postgresql
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/almedin_db}
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}

# Generacion de las tablas
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Configuracion de REST y JSON
quarkus.jackson.write-dates-as-timestamps=false

# Configuracion de OpenAPI y SwaggerUI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
mp.openapi.extensions.smallrye.info.title=Almedin Obra Social API
mp.openapi.extensions.smallrye.info.version=1.0.0

# MapStruct
quarkus.mapstruct.injection-strategy=constructor

# Docker

# JWT
mp.jwt.verify.publickey.location=keys/public.pem
mp.jwt.verify.issuer=almedin-backend
smallrye.jwt.sign.key.location=keys/private.pem